<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>Lifecycle.Tests</AssemblyName><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="..\..\src\Lifecycle.NET\Lifecycle.NET.csproj" /><ProjectReference Include="..\..\src\Lifecycle.Graph\Lifecycle.Graph.csproj" /><ProjectReference Include="..\..\src\Lifecycle.Diagnostics\Lifecycle.Diagnostics.csproj" /><ProjectReference Include="..\..\src\Lifecycle.Hosting\Lifecycle.Hosting.csproj" /></ItemGroup></Project>
