using Lifecycle;
using Lifecycle.Graph;
using Lifecycle.Diagnostics;
using Lifecycle.Hosting;

var tests = new (string Name, Func<Task> Run)[] { ("valid transitions invoke hooks", ValidTransitions), ("invalid transitions are rejected", InvalidTransition), ("state waiting observes a transition", StateWaiting), ("timeouts include middleware retry delays", TimeoutCoversRetry), ("middleware surrounds a hook", MiddlewareOrdering), ("retry middleware recovers transient failure", RetryRecovery), ("recover operation returns to initialized", RecoveryOperation), ("supervisor heals a failed service", SupervisorRecovery), ("leases drain before stop", LeaseDrain), ("diagnostics records transitions", Diagnostics), ("hosting rejects failed lifecycle", HostingRejectsFailed), ("hosting starts and stops in deterministic order", HostingOrdering), ("graph validates cycles structurally", GraphValidation), ("graph dry run exposes waves", GraphDryRun), ("atomic transaction rolls back", TransactionRollback), ("graph starts dependencies first", GraphOrdering) };
var failures = new List<string>();
foreach (var test in tests) { try { await test.Run(); Console.WriteLine($"PASS {test.Name}"); } catch (Exception ex) { failures.Add($"{test.Name}: {ex.Message}"); Console.Error.WriteLine($"FAIL {test.Name}: {ex}"); } }
return failures.Count == 0 ? 0 : 1;

static async Task ValidTransitions() { var item = new Probe(); await item.InitializeAsync(); await item.StartAsync(); await item.PauseAsync(); await item.ResumeAsync(); await item.StopAsync(); Assert(item.Events.SequenceEqual(["initialize", "start", "pause", "resume", "stop"])); Assert(item.State == LifecycleState.Stopped); }
static async Task InvalidTransition() { var item = new Probe(); await AssertThrows<LifecycleTransitionException>(() => item.StartAsync()); }
static async Task StateWaiting() { var item = new Probe(); var wait = item.WaitForRunningAsync(); await item.InitializeAsync(); await item.StartAsync(); await wait.WaitAsync(TimeSpan.FromSeconds(1)); }
static async Task TimeoutCoversRetry() { var item = new AlwaysFailingProbe(); await AssertThrows<OperationCanceledException>(() => item.InitializeAsync()); Assert(item.Attempts == 1); }
static async Task MiddlewareOrdering() { var log = new List<string>(); var item = new Probe(middleware: [new RecordingMiddleware(log)]); await item.InitializeAsync(); Assert(log.SequenceEqual(["before", "after"])); }
static async Task RetryRecovery() { var item = new FlakyProbe(); await item.InitializeAsync(); Assert(item.Attempts == 2); Assert(item.State == LifecycleState.Initialized); }
static async Task RecoveryOperation() { var item = new RecoveryProbe(); await item.InitializeAsync(); await AssertThrows<InvalidOperationException>(() => item.StartAsync()); await item.RecoverAsync(); Assert(item.Recovered && item.State == LifecycleState.Initialized); }
static async Task SupervisorRecovery() { var item = new RecoveryProbe(); using var supervisor = new LifecycleSupervisor(new LifecycleSupervisorOptions { RecoveryDelay = TimeSpan.Zero }); supervisor.Supervise(item); await item.InitializeAsync(); await AssertThrows<InvalidOperationException>(() => item.StartAsync()); await item.WaitForRunningAsync().WaitAsync(TimeSpan.FromSeconds(1)); Assert(item.Recovered && item.State == LifecycleState.Running); }
static async Task LeaseDrain() { var item = new Probe(); await item.InitializeAsync(); await item.StartAsync(); var first = await item.AcquireLeaseAsync(); var second = await item.AcquireLeaseAsync(); var stop = item.StopAsync(); await Task.Delay(20); Assert(!stop.IsCompleted && item.ActiveLeaseCount == 2); first.Dispose(); await Task.Delay(20); Assert(!stop.IsCompleted); await second.DisposeAsync(); await stop.WaitAsync(TimeSpan.FromSeconds(1)); Assert(item.State == LifecycleState.Stopped && item.ActiveLeaseCount == 0); }
static async Task Diagnostics() { var item = new Probe(); using var diagnostics = new LifecycleDiagnostics(); diagnostics.Track("probe", item); await item.InitializeAsync(); var snapshot = diagnostics.GetSnapshot(); Assert(snapshot.Transitions == 1 && snapshot.StateCounts[LifecycleState.Initialized] == 1 && diagnostics.GetHistory().Single().Name == "probe"); }
static async Task HostingOrdering() { var log = new List<string>(); var host = new LifecycleHostedService([new NamedProbe("one", log), new NamedProbe("two", log)]); await host.StartAsync(CancellationToken.None); await host.StopAsync(CancellationToken.None); Assert(log.SequenceEqual(["one:init", "one:start", "two:init", "two:start", "two:stop", "one:stop"])); }
static async Task HostingRejectsFailed() { var item = new RecoveryProbe(); await item.InitializeAsync(); await AssertThrows<InvalidOperationException>(() => item.StartAsync()); var host = new LifecycleHostedService([item]); await AssertThrows<InvalidOperationException>(() => host.StartAsync(CancellationToken.None)); }
static Task GraphValidation() { var graph = new LifecycleGraphBuilder().Add("a", new Probe(), "b").Add("b", new Probe(), "a").Build(); var validation = graph.Validate(); Assert(!validation.IsValid && validation.Issues.Single().Code == LifecycleGraphValidationCode.CycleDetected); return Task.CompletedTask; }
static async Task GraphDryRun() { var graph = new LifecycleGraphBuilder().Add("database", new Probe()).Add("api", new Probe(), "database").Build(); var report = await graph.DryRunStartAsync(); Assert(report.Snapshot.Waves.Count == 2 && report.RollbackOrder.Select(id => id.Value).SequenceEqual(["api", "database"])); }
static async Task TransactionRollback() { var log = new List<string>(); var graph = new LifecycleGraphBuilder().Add("database", new NamedProbe("database", log)).Add("cache", new NamedProbe("cache", log), "database").Add("zbus", new StartFailingProbe("zbus", log), "database").Build(); var result = await graph.BeginTransaction("startup", options: new LifecycleExecutionOptions { MaximumParallelism = 1 }).StartAsync(); Assert(!result.Succeeded && result.RolledBackNodes.Select(id => id.Value).SequenceEqual(["cache", "database"])); Assert(log.SequenceEqual(["database:init", "database:start", "cache:init", "cache:start", "zbus:init", "zbus:start", "cache:stop", "database:stop"])); }
static async Task GraphOrdering() { var log = new List<string>(); var database = new Probe(log); var api = new Probe(log); var graph = new LifecycleGraphBuilder().Add("database", database).Add("api", api, "database").Build(); await graph.StartAsync(); Assert(log.SequenceEqual(["initialize", "start", "initialize", "start"])); await graph.StopAsync(); }
static async Task AssertThrows<T>(Func<Task> action) where T : Exception { try { await action(); } catch (T) { return; } throw new Exception($"Expected {typeof(T).Name}."); }
static void Assert(bool value) { if (!value) throw new Exception("Assertion failed."); }
sealed class Probe(List<string>? events = null, IEnumerable<ILifecycleMiddleware>? middleware = null) : LifecycleObject(middleware: middleware)
{ public List<string> Events { get; } = events ?? []; protected override Task OnInitializeAsync(CancellationToken token) { Events.Add("initialize"); return Task.CompletedTask; } protected override Task OnStartAsync(CancellationToken token) { Events.Add("start"); return Task.CompletedTask; } protected override Task OnPauseAsync(CancellationToken token) { Events.Add("pause"); return Task.CompletedTask; } protected override Task OnResumeAsync(CancellationToken token) { Events.Add("resume"); return Task.CompletedTask; } protected override Task OnStopAsync(CancellationToken token) { Events.Add("stop"); return Task.CompletedTask; } }
sealed class RecordingMiddleware(List<string> log) : ILifecycleMiddleware { public async Task InvokeAsync(LifecycleTransitionContext context, LifecycleTransitionDelegate next) { log.Add("before"); await next(context); log.Add("after"); } }
sealed class FlakyProbe() : LifecycleObject(middleware: [new RetryMiddleware(new RetryOptions { MaxAttempts = 2, InitialDelay = TimeSpan.Zero })]) { public int Attempts { get; private set; } protected override Task OnInitializeAsync(CancellationToken token) { Attempts++; if (Attempts == 1) throw new InvalidOperationException("transient"); return Task.CompletedTask; } }
sealed class AlwaysFailingProbe() : LifecycleObject(new LifecycleOptions { InitializeTimeout = TimeSpan.FromMilliseconds(30) }, [new RetryMiddleware(new RetryOptions { MaxAttempts = 4, InitialDelay = TimeSpan.FromSeconds(1) })]) { public int Attempts { get; private set; } protected override Task OnInitializeAsync(CancellationToken token) { Attempts++; throw new InvalidOperationException("always fails"); } }
class NamedProbe(string name, List<string> log) : LifecycleObject { protected override Task OnInitializeAsync(CancellationToken token) { log.Add($"{name}:init"); return Task.CompletedTask; } protected override Task OnStartAsync(CancellationToken token) { log.Add($"{name}:start"); return Task.CompletedTask; } protected override Task OnStopAsync(CancellationToken token) { log.Add($"{name}:stop"); return Task.CompletedTask; } }
sealed class StartFailingProbe(string name, List<string> log) : NamedProbe(name, log) { protected override Task OnStartAsync(CancellationToken token) { _ = base.OnStartAsync(token); throw new InvalidOperationException("start failure"); } }
sealed class RecoveryProbe : LifecycleObject { private bool _failFirstStart = true; public bool Recovered { get; private set; } protected override Task OnStartAsync(CancellationToken token) { if (_failFirstStart) { _failFirstStart = false; throw new InvalidOperationException("startup fault"); } return Task.CompletedTask; } protected override Task OnRecoverAsync(CancellationToken token) { Recovered = true; return Task.CompletedTask; } }
