<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AssemblyName>Lifecycle.Extensions.DependencyInjection</AssemblyName><RootNamespace>Microsoft.Extensions.DependencyInjection</RootNamespace><PackageId>Magnexis.Lifecycle.Extensions.DependencyInjection</PackageId><Description>Microsoft dependency injection integration for Lifecycle.NET.</Description></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><ProjectReference Include="..\Lifecycle.Abstractions\Lifecycle.Abstractions.csproj" /></ItemGroup></Project>
